// <auto-generated />
using System;
using EatHealthyCycle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EatHealthyCycle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("EatHealthyCycle.Models.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComidaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Comida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DietaDiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DietaDiaId");

                    b.ToTable("Comidas");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Dieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivoOriginal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Dietas");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.DietaDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DietaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DietaId");

                    b.ToTable("DietaDias");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.ItemListaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Comprado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanSemanalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanSemanalId");

                    b.ToTable("ItemsListaCompra");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.PlanComida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComidaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanDiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.HasIndex("PlanDiaId");

                    b.ToTable("PlanComidas");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.PlanDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanSemanalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanSemanalId");

                    b.ToTable("PlanDias");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.PlanSemanal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DietaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DietaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PlanesSemanal");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.RegistroPeso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique();

                    b.ToTable("RegistrosPeso");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivationTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryCodes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@eathealthycycle.local",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Admin",
                            PasswordHash = "$2a$11$r1zN2HmMy2FnebH4onffcOzWj8IsqmrB0Yxe5k1VgbPzXOh29WGDm",
                            Role = 3,
                            TwoFactorEnabled = false,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Alimento", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.Comida", "Comida")
                        .WithMany("Alimentos")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Comida", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.DietaDia", "DietaDia")
                        .WithMany("Comidas")
                        .HasForeignKey("DietaDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaDia");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Dieta", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.Usuario", "Usuario")
                        .WithMany("Dietas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.DietaDia", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.Dieta", "Dieta")
                        .WithMany("Dias")
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.ItemListaCompra", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.PlanSemanal", "PlanSemanal")
                        .WithMany("ItemsListaCompra")
                        .HasForeignKey("PlanSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanSemanal");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.PlanComida", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.Comida", "Comida")
                        .WithMany()
                        .HasForeignKey("ComidaId");

                    b.HasOne("EatHealthyCycle.Models.PlanDia", "PlanDia")
                        .WithMany("Comidas")
                        .HasForeignKey("PlanDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");

                    b.Navigation("PlanDia");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.PlanDia", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.PlanSemanal", "PlanSemanal")
                        .WithMany("Dias")
                        .HasForeignKey("PlanSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanSemanal");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.PlanSemanal", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.Dieta", "Dieta")
                        .WithMany()
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EatHealthyCycle.Models.Usuario", "Usuario")
                        .WithMany("PlanesSemanal")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.RegistroPeso", b =>
                {
                    b.HasOne("EatHealthyCycle.Models.Usuario", "Usuario")
                        .WithMany("RegistrosPeso")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Comida", b =>
                {
                    b.Navigation("Alimentos");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Dieta", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.DietaDia", b =>
                {
                    b.Navigation("Comidas");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.PlanDia", b =>
                {
                    b.Navigation("Comidas");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.PlanSemanal", b =>
                {
                    b.Navigation("Dias");

                    b.Navigation("ItemsListaCompra");
                });

            modelBuilder.Entity("EatHealthyCycle.Models.Usuario", b =>
                {
                    b.Navigation("Dietas");

                    b.Navigation("PlanesSemanal");

                    b.Navigation("RegistrosPeso");
                });
#pragma warning restore 612, 618
        }
    }
}
